//Define and export constants

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const HANDLE_CLOSE_REQUEST = "HANDLE_CLOSE_REQUEST";
